# Generated by Django 5.2.5 on 2025-09-15 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_course_type_course_instructor'),
        ('student', '0003_remove_student_course_id_alter_student_grade_id_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_form_templates', to='courses.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teachers')),
            ],
            options={
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.CreateModel(
            name='DynamicGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_components', models.JSONField(default=dict, help_text='JSON object containing grade components and their values')),
                ('final_grade', models.CharField(blank=True, choices=[('A', 'A (Excellent)'), ('B', 'B (Very Good)'), ('C', 'C (Good)'), ('D', 'D (Satisfactory)'), ('F', 'F (Fail)'), ('I', 'Incomplete'), ('W', 'Withdrawn')], max_length=2, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Total score calculated from grade components', max_digits=5, null=True)),
                ('max_possible_score', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum possible score for this course', max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score (total_score / max_possible_score * 100)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this grade record is active or inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_grades', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_grades', to='student.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_grades', to='teacher.teachers')),
            ],
            options={
                'verbose_name': 'Dynamic Grade',
                'verbose_name_plural': 'Dynamic Grades',
                'indexes': [models.Index(fields=['student', 'course'], name='grades_dyna_student_5ec6e7_idx'), models.Index(fields=['teacher'], name='grades_dyna_teacher_795ff5_idx'), models.Index(fields=['is_active'], name='grades_dyna_is_acti_1989dc_idx'), models.Index(fields=['final_grade'], name='grades_dyna_final_g_573f53_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='GradeComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight of this component in final grade calculation (1.0 = 100%)', max_digits=4)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='grades.gradeformtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form_template', 'name')},
            },
        ),
    ]
