# Generated by Django 5.2.5 on 2025-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_type_course_instructor'),
        ('grades', '0001_initial'),
        ('student', '0003_remove_student_course_id_alter_student_grade_id_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicgrade',
            name='is_approved',
            field=models.BooleanField(blank=True, help_text='Whether this grade has been approved by the administration', null=True),
        ),
        migrations.AlterField(
            model_name='dynamicgrade',
            name='final_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (Excellent)'), ('A', 'A (Very Good)'), ('A-', 'A- (Good)'), ('B+', 'B+ (Very Good)'), ('B', 'B (Good)'), ('B-', 'B- (Satisfactory)'), ('C+', 'C+ (Satisfactory)'), ('C', 'C (Passing)'), ('C-', 'C- (Marginal)'), ('D', 'D (Poor)'), ('F', 'F (Fail)'), ('I', 'Incomplete'), ('W', 'Withdrawn')], max_length=3, null=True),
        ),
        migrations.AddIndex(
            model_name='dynamicgrade',
            index=models.Index(fields=['is_approved'], name='grades_dyna_is_appr_33d9a7_idx'),
        ),
    ]
