# Generated by Django 5.2.5 on 2025-08-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAuths',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_count', models.PositiveIntegerField(editable=False)),
                ('firstName', models.CharField(max_length=100)),
                ('fatherName', models.CharField(max_length=100)),
                ('grandFatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(blank=True, max_length=100, null=True)),
                ('mothersFatherName', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('entrance_exam', models.CharField(blank=True, max_length=100, null=True)),
                ('catagory', models.CharField(blank=True, choices=[('Natural Science', 'Natural Science'), ('Social Science', 'Social Science'), ('Other', 'Other')], max_length=30, null=True)),
                ('role', models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Department Head', 'Department Head'), ('College Head', 'College Head'), ('President', 'President'), ('Admin', 'Admin')], default='student', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('password', models.CharField(default='pbkdf2_sha256$1000000$FdrsPRFYckCEXFWzHtKVR9$h8rQhTDzEArKoxyWRXCLx8H7ueemR4fg55pDKtuBgx8=', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_pictures/')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_or_special_wereda', models.CharField(blank=True, max_length=100, null=True)),
                ('city_or_town', models.CharField(blank=True, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('handicap', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
