# Generated by Django 5.2.5 on 2025-08-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAuths',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstName', models.CharField(max_length=200)),
                ('fatherName', models.CharField(max_length=200)),
                ('grandFatherName', models.CharField(max_length=200)),
                ('motherName', models.CharField(blank=True, max_length=200, null=True)),
                ('mothersFatherName', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('entrance_exam', models.CharField(blank=True, max_length=100, null=True)),
                ('catagory', models.CharField(blank=True, choices=[('Natural Science', 'Natural Science'), ('Social Science', 'Social Science'), ('Other', 'Other')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('student', 'student'), ('registeral', 'registeral'), ('teacher', 'teacher'), ('department Head', 'department Head'), ('college Head', 'college Head'), ('president', 'president'), ('admin', 'admin')], default='student', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('userId', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(default='pbkdf2_sha256$1000000$SwnP71vMf16iyN95XJbV53$Ewet63zkZh8XVvpX7DVeL9scEms8erhYpQRDoRb0wog=', max_length=255)),
                ('is_default_password', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('zone_or_special_wereda', models.CharField(blank=True, max_length=200, null=True)),
                ('city_or_town', models.CharField(blank=True, max_length=200, null=True)),
                ('house_number', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=200, null=True)),
                ('handicap', models.CharField(blank=True, choices=[('normal', 'normal'), ('case', 'case')], default='normal', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'userId'], name='user_usersa_usernam_3f39c3_idx'), models.Index(fields=['firstName', 'fatherName'], name='user_usersa_firstNa_0d1d6d_idx')],
            },
        ),
    ]
