# Generated by Django 5.2.5 on 2025-08-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Fw4zSD2yMlC9bTGvUF6Odi$CF/l55XzVkLR1BKoFY27L4WoZjTMd62fAFxeBhYfBhI=', max_length=255),
        ),
    ]
