# Generated by Django 5.2.5 on 2025-08-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$2iduzpka64y4JAYi0VjqHo$k2VIXM6TNPjyJnrMSDzH1Zqo2ZhMmp67zhPW6ZOjOBw=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='user_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
