# Generated by Django 5.2.5 on 2025-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$JanHgItfkz0uIVQSgQXpVt$sTeFJ+4313IGnrbMq9QmqHwDWELpKW3UsAsFMnUOAcI=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Department Head', 'Department Head'), ('College Head', 'College Head'), ('President', 'President'), ('Admin', 'Admin')], default='student', max_length=20),
        ),
    ]
