# Generated by Django 5.2.5 on 2025-08-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usersauths_password_alter_usersauths_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersauths',
            name='is_default_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$j7epFo3UCb3hqOMKdZjjda$QPYMUmtjyX9XVM027WWCKqeR4mYS/K0Xlm1PjUiXTBA=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('registeral', 'registeral'), ('teacher', 'teacher'), ('department Head', 'department Head'), ('college Head', 'college Head'), ('president', 'president'), ('admin', 'admin')], default='student', max_length=20),
        ),
    ]
