# Generated by Django 5.2.5 on 2025-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Tf0oH9nmKkV3ijqsYeWzD4$NE+gCHpe2+vM11vX20bXuCiQgwtrTf0/iPxKBD97bWI=', max_length=255),
        ),
    ]
