# Generated by Django 5.2.5 on 2025-08-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usersauths_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$ZW8GA0pPkrn25JKCedkFQQ$LwGSJxrD5YRuOAqgjQZJfGyNd9iRYQador00XFKfmyA=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='user_count',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
