# Generated by Django 5.2.5 on 2025-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usersauths_is_default_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$3V3koutZzAKcc3nTVzhjs8$FzYD82m5DQqsfq/JaM38ZzhNSFodPWcuePzH1txDtzY=', max_length=255),
        ),
    ]
