# Generated by Django 5.2.5 on 2025-08-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersauths',
            options={'verbose_name': 'User Auth', 'verbose_name_plural': 'Users Auths'},
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$BQM90lDyWr0zRPwA3cVmsy$zkYJMr3QLEC1Px64jXvOWzkJrZv5/PvABacqqwixTVs=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/%d/'),
        ),
    ]
