# Generated by Django 5.2.5 on 2025-08-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usersauths_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersauths',
            name='user_count',
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Kal5qdnsU0ffCq6tV4Zmkh$H6tGYinutwz+unExMa1UoR9no2wnOyFVftn1/l8P3V8=', max_length=255),
        ),
    ]
