# Generated by Django 5.2.5 on 2025-09-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usersauths_options_alter_usersauths_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$xBv29xWyZmAw8rcAuhf12h$rOduETxHms+1ha6FEep11KcKJFRgM1lxCysIFIxNzg8=', max_length=255),
        ),
    ]
