# Generated by Django 5.2.5 on 2025-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$XX3ALnl8KnZcwxH23atyeU$1NB2biqN2mz0vwfedwfYnNmpqma1QNHBQVdzsZnLgL8=', max_length=255),
        ),
    ]
