# Generated by Django 5.2.5 on 2025-08-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$5GMYI5QiR085LKu0LpPrEo$rjfTfChOGm0fPIEp3fj/et+Kmu8xfTysrxPP9rTipwo=', max_length=255),
        ),
    ]
