# Generated by Django 5.2.5 on 2025-09-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$f203cyttSiXkatf869mGYi$u9Z5sIx2MSfT7v0tbPFTOLngBo28XXAIMbv68XHq9Us=', max_length=255),
        ),
    ]
