# Generated by Django 5.2.5 on 2025-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$6wlvMamzXU6QkGlBzOHA33$1fRdDnmtiuvomcNovbJyAStB0oKZmDaRE1SAgOsy1aM=', max_length=255),
        ),
    ]
