# Generated by Django 5.2.5 on 2025-09-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$00rPazcZYHP9RxZKuHWoBC$U5rf+g5zR7ux5auIumqK9aaQghlLysv92Rr1lN9dUSo=', max_length=255),
        ),
    ]
