# Generated by Django 5.2.5 on 2025-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$oepj2aWOdkjpWQOEUdEZfv$cqTZDUIRapPLHAcZgCdbZTNzRDh8s7ZsPYWLWlLa304=', max_length=255),
        ),
    ]
