# Generated by Django 5.2.5 on 2025-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$LPW74HQPxm1gvWC6UAfa2Y$UD7O2EsnEMKoKIIuV0KifiN0v4od2tng/IM5S+YGzdY=', max_length=255),
        ),
    ]
