# Generated by Django 5.2.5 on 2025-08-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$RGkLDLsE8pQkgQlkK18Cw9$nknLw3sFt+WYUp4qOoGH57w3vAT/dpTGgrYee+9+Tsg=', max_length=255),
        ),
    ]
