# Generated by Django 5.2.5 on 2025-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usersauths_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersauths',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='catagory',
            field=models.CharField(blank=True, choices=[('Natural Science', 'Natural Science'), ('Social Science', 'Social Science'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='city_or_town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='fatherName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='firstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='grandFatherName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='handicap',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('case', 'case')], default='normal', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='house_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='motherName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='mothersFatherName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='nationality',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$MpZOap3AMqoP08xxrAcyt6$AyzoJzI4LJtZp91td53EuLvMbuMF48kj8D0m8g9tCP4=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='religion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('registeral', 'registeral'), ('teacher', 'teacher'), ('department Head', 'department Head'), ('college Head', 'college Head'), ('president', 'president'), ('admin', 'admin')], default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='userId',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='zone_or_special_wereda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
