# Generated by Django 5.2.5 on 2025-09-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$JFzO3mXQPNQejw6tez9wJj$kZ26ct80sKE3cLVE5CPsBsp0cULFmKBqoCBvevQFdPM=', max_length=255),
        ),
    ]
