# Generated by Django 5.2.5 on 2025-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_usersauths_position_alter_usersauths_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$i3fehjTPakqjApJ2oHd8ve$YmlpQQsEU+JUrr4O8t49hKvT1qHinP0DS0VPGW6klzg=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='position',
            field=models.CharField(blank=True, choices=[('collage_head', 'collage_head'), ('department_head', 'department_head'), ('peresdant', 'peresdant'), ('registeral', 'registeral'), ('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student')], default='student', max_length=100, null=True),
        ),
    ]
