# Generated by Django 5.2.5 on 2025-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$o5rNxjomm8K0eJRf3x6zcH$bL3rKDbIjz5npZitCrL6qC90FbkbHACA9DOfj/MfcSs=', max_length=255),
        ),
    ]
