# Generated by Django 5.2.5 on 2025-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_usersauths_password_alter_usersauths_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$xvJRBZXjB9Sw5DThmDmX9z$CQMBx8KYjf5tMR4r3n2xMUb3Mi/xJwWiaQYSuVxzMYI=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='position',
            field=models.CharField(blank=True, choices=[('collage_head', 'collage_head'), ('department_head', 'department_head'), ('peresdant', 'peresdant'), ('registeral', 'registeral'), ('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student')], max_length=100, null=True),
        ),
    ]
