# Generated by Django 5.2.5 on 2025-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$pcfuYPUoX11n6xPndq1qRg$YCtup4iDuMYySqRYM2M/2GQeudilOejVF4oDkI+mKQA=', max_length=255),
        ),
    ]
