# Generated by Django 5.2.5 on 2025-09-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$NASnAROJFUKK8Q1hz4HBx8$Crx4Jb3oILH/mTVHzP9DcKoRMyGC9kZzRc1MXBCDNOc=', max_length=255),
        ),
    ]
