# Generated by Django 5.2.5 on 2025-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_usersauths_password_alter_usersauths_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$MHq8GQG5FVtXan9qNDcfyf$CMjgwZ0klLqNjunp1ZaQT6SmOm8zR1rVP2MWaokkYYI=', max_length=255),
        ),
    ]
