# Generated by Django 5.2.5 on 2025-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$TWuG89y2exYsbNcn1Fvm3g$PK6EVX9gLzfrFZa3HMxbT8F9HsHaxGfJIYwzzSyqM88=', max_length=255),
        ),
    ]
