# Generated by Django 5.2.5 on 2025-09-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$fW44x0q0UNzfyT0kbHSjQp$gjsF9K+F1gVmN5dFOBTaIvv+5EvJ6fzkSntb9TfS7YA=', max_length=255),
        ),
    ]
