# Generated by Django 5.2.5 on 2025-09-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$F7P637JUH1tWucKFVuTew7$c7FTN+AUO0inV/MN/tGxUyjRFHRddsPw5rhb36CYmJQ=', max_length=255),
        ),
    ]
