# Generated by Django 5.2.5 on 2025-09-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Vp5E5lLpXo8mbfuLUZJQXL$AaBW5EI/S05wuRfI1a7g67KJq/aSV6VTGfs1cKsHGy8=', max_length=255),
        ),
    ]
