# Generated by Django 5.2.5 on 2025-09-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$x5eC2vNZFdAsh7On7WqUuJ$wWBaevuOnWBmAuygijUNuSsSL7vi33Ww0BQnuYTNGfI=', max_length=255),
        ),
    ]
