# Generated by Django 5.2.5 on 2025-09-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$JQsC09xxNnBArnTcrEWFCV$57Ypjpkavu3EttcdPtaIW/GGIuabUTYP7jZeGlX7ZxE=', max_length=255),
        ),
    ]
