# Generated by Django 5.2.5 on 2025-09-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$IXQYRQ05GG6HyEpUVji5FI$tZ9xzTHU6sZjrpvnLU2GNJ5hDJUvYz5TPuBX33kUtG4=', max_length=255),
        ),
    ]
