# Generated by Django 5.2.5 on 2025-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$oMrQ4FyhhFvpsydGv1g7Sd$0Q63tr/GEWdN6VYh2q+aC8bVBkG5gwJw30cDN4mhK9Q=', max_length=255),
        ),
    ]
