# Generated by Django 5.2.5 on 2025-10-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$e9wRC3C7uLDYqYxB6iMTak$QEfwjXFzRb6kzbo4SMbYi3joJbMALOp61A0RalWcIkc=', max_length=255),
        ),
    ]
