# Generated by Django 5.2.5 on 2025-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$pq9C8d5g4gDsDmqWIEOEet$wwhyHF0D7yV/A/XEPFt+Xa/bEsxLV6Dd2Cyor4miLKU=', max_length=255),
        ),
    ]
