# Generated by Django 5.2.5 on 2025-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_usersauths_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersauths',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$JCAYHB9hJnnDs5mhG868ko$duRGhGDCOMP05xG2yHIrRCmi43pL1ELXuIrjjoblZ4A=', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersauths',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('registeral', 'registeral'), ('teacher', 'teacher'), ('department', 'department'), ('collage', 'collage'), ('president', 'president'), ('admin', 'admin')], default='student', max_length=50),
        ),
    ]
