# Generated by Django 5.2.5 on 2025-08-20 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=200)),
                ('course_department', models.CharField(max_length=100)),
                ('course_credit', models.PositiveSmallIntegerField(default=3)),
                ('course_taken_year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year'), ('6', '6th Year'), ('7', '7th Year')], max_length=1)),
                ('course_taken_semester', models.CharField(choices=[('I', 'Semester I'), ('II', 'Semester II')], max_length=2)),
                ('course_category', models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD')], default='BSc', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_courses', to='courses.course')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['course_code'],
            },
        ),
    ]
