# Generated by Django 5.2.5 on 2025-08-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('course_credit', models.PositiveIntegerField()),
                ('course_taken_year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year'), ('6th', '6th Year'), ('7th', '7th Year')], default='1st', max_length=3)),
                ('course_taken_semester', models.CharField(choices=[('I', 'Semester I'), ('II', 'Semester II')], default='I', max_length=2)),
                ('course_category', models.CharField(choices=[('BSc', 'Bachelor of Science'), ('MSc', 'Master of Science'), ('PhD', 'Doctor of Philosophy')], default='BSc', max_length=3)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collages.department')),
            ],
        ),
    ]
