# Generated by Django 5.2.5 on 2025-09-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('compulsory', 'Compulsory'), ('supporting', 'Supporting'), ('common', 'Common'), ('elective', 'Elective')], default='compulsory', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
