# Generated by Django 5.2.5 on 2025-08-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year'), ('6th', '6th Year'), ('7th', '7th Year')], default='1st', max_length=3)),
                ('semester', models.CharField(choices=[('I', 'Semester I'), ('II', 'Semester II')], default='I', max_length=2)),
                ('course_category', models.CharField(choices=[('BSc', 'Bachelor of Science'), ('MSc', 'Master of Science'), ('PhD', 'Doctor of Philosophy')], default='BSc', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quiz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('participation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
