# Generated by Django 5.2.5 on 2025-08-23 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collages', '0001_initial'),
        ('courses', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collages.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
