# Generated by Django 5.2.5 on 2025-09-06 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collages', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('academic_level', models.CharField(choices=[('BSc', 'Bachelor of Science'), ('MSc', 'Master of Science'), ('PhD', 'Doctor of Philosophy'), ('Professor', 'Professor')], default='BSc', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collages.college')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TeachersCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year'), ('6th', '6th Year'), ('7th', '7th Year')], max_length=3)),
                ('semester', models.CharField(choices=[('I', 'Semester I'), ('II', 'Semester II')], max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teachers')),
            ],
            options={
                'verbose_name': 'Teacher Course Assignment',
                'verbose_name_plural': 'Teacher Course Assignments',
            },
        ),
        migrations.AddIndex(
            model_name='teachers',
            index=models.Index(fields=['teacher_id', 'username'], name='teacher_tea_teacher_758645_idx'),
        ),
        migrations.AddIndex(
            model_name='teachers',
            index=models.Index(fields=['college_id'], name='teacher_tea_college_dab2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherscourse',
            index=models.Index(fields=['teacher_id', 'course_id'], name='teacher_tea_teacher_a4791a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherscourse',
            index=models.Index(fields=['batch', 'year', 'semester'], name='teacher_tea_batch_df49dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherscourse',
            unique_together={('teacher_id', 'course_id', 'batch', 'year', 'semester')},
        ),
    ]
