# Generated by Django 5.2.5 on 2025-08-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collages.college')),
            ],
        ),
    ]
