# Generated by Django 5.2.5 on 2025-08-21 10:47

import collages.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255, validators=[collages.models.validate_department_name])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='collages.collages')),
            ],
        ),
    ]
