# Generated by Django 5.2.5 on 2025-08-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='collage',
            new_name='college',
        ),
    ]
